# Generated by Django 4.1.7 on 2023-03-10 22:24

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('country', django_countries.fields.CountryField(max_length=2, verbose_name='Страна')),
                ('city', models.CharField(max_length=1024, verbose_name='Город')),
                ('street', models.CharField(max_length=1024, verbose_name='Улица')),
                ('street_number', models.CharField(max_length=50, verbose_name='Номер дома')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('contacts', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_unit', to='units.contacts', verbose_name='Контакты')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
            },
        ),
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('supplier_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='units.supplier')),
            ],
            options={
                'verbose_name': 'Завод',
                'verbose_name_plural': 'Заводы',
            },
            bases=('units.supplier',),
        ),
        migrations.CreateModel(
            name='Retailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('amount_due', models.BigIntegerField()),
                ('contacts', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_unit', to='units.contacts', verbose_name='Контакты')),
                ('products', models.ManyToManyField(related_name='retail_outlets', to='products.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retail_outlets', to='units.supplier', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Розница',
                'verbose_name_plural': 'Розница',
            },
        ),
        migrations.CreateModel(
            name='Wholesaler',
            fields=[
                ('supplier_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='units.supplier')),
                ('amount_due', models.BigIntegerField()),
                ('products', models.ManyToManyField(related_name='wholesalers', to='products.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wholesalers', to='units.factory', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Оптовик',
                'verbose_name_plural': 'Оптовики',
            },
            bases=('units.supplier',),
        ),
    ]
