# Generated by Django 4.1.7 on 2023-03-09 01:40

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('country', django_countries.fields.CountryField(max_length=2, verbose_name='Страна')),
                ('city', models.CharField(max_length=1024, verbose_name='Город')),
                ('street', models.CharField(max_length=1024, verbose_name='Улица')),
                ('str_num', models.CharField(max_length=50, verbose_name='Номер дома')),
            ],
        ),
    ]
