# Generated by Django 4.1.7 on 2023-03-11 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0003_alter_retailer_name_alter_supplier_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Factory',
            new_name='FactoryUnit',
        ),
    ]
